__title__ = 'Flask-Market_Place'
__description__ = 'match market'
__url__ = '  '
__version_info__ = ('0', '0', '0')
__version__ = '.'.join(__version_info__)
__author__ = 'Revital Matityahu $ Eran Sarid'
__author_email__ = ''
__maintainer__ = ''
__license__ = ''
__copyright__ = ''